k8 test

diff --git a/.github/workflows/build_deploy.yml b/.github/workflows/build_deploy.yml
--- a/.github/workflows/build_deploy.yml
+++ b/.github/workflows/build_deploy.yml
@@ -8,38 +8,38 @@ on:
 
 jobs:
 
-  compile:
-    runs-on: self-hosted
-    steps:
-    - uses: actions/checkout@v4
-    - name: Set up JDK 17
-      uses: actions/setup-java@v4
-      with:
-        java-version: '17'
-        distribution: 'temurin'
-        cache: maven
-    - name: Compile with Maven
-      run: mvn compile
+  # compile:
+  #   runs-on: self-hosted
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #   - name: Set up JDK 17
+  #     uses: actions/setup-java@v4
+  #     with:
+  #       java-version: '17'
+  #       distribution: 'temurin'
+  #       cache: maven
+  #   - name: Compile with Maven
+  #     run: mvn compile
 
-  build_test:
-    runs-on: self-hosted
-    needs: compile
-    steps:
-    - uses: actions/checkout@v4
-    - name: Set up JDK 17
-      uses: actions/setup-java@v4
-      with:
-        java-version: '17'
-        distribution: 'temurin'
-        cache: maven
-    - name: Build_And_Test with Maven
-      run: mvn test package -Dmaven.test.failure.ignore=true --file pom.xml
-    - name: Archive Artifacts
-      if: success() || failure()
-      uses: actions/upload-artifact@v4
-      with:
-        name: app-jar
-        path: target/*.jar
+  # build_test:
+  #   runs-on: self-hosted
+  #   needs: compile
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #   - name: Set up JDK 17
+  #     uses: actions/setup-java@v4
+  #     with:
+  #       java-version: '17'
+  #       distribution: 'temurin'
+  #       cache: maven
+  #   - name: Build_And_Test with Maven
+  #     run: mvn test package -Dmaven.test.failure.ignore=true --file pom.xml
+  #   - name: Archive Artifacts
+  #     if: success() || failure()
+  #     uses: actions/upload-artifact@v4
+  #     with:
+  #       name: app-jar
+  #       path: target/*.jar
   
   # sonarScan:
   #   runs-on: self-hosted
@@ -87,31 +87,48 @@ jobs:
   #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
   #       SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
 
-  Build_docker_image: 
-    runs-on: self-hosted
-    needs: build_test
-    steps:
-    - uses: actions/checkout@v4
-    - name: Download Artifacts
-      uses: actions/download-artifact@v4
-      with:
-        name: app-jar
-        path: target
+  # Build_docker_image: 
+  #   runs-on: self-hosted
+  #   needs: build_test
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #   - name: Download Artifacts
+  #     uses: actions/download-artifact@v4
+  #     with:
+  #       name: app-jar
+  #       path: target
 
-    - name: Log in to Docker Hub
-      uses: docker/login-action@v2
+  #   - name: Log in to Docker Hub
+  #     uses: docker/login-action@v2
+  #     with:
+  #       username: ${{ secrets.DOCKER_HUB_USERNAME }}
+  #       password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
+  #   - name: Set up QEMU
+  #     uses: docker/setup-qemu-action@v3
+  #   - name: Set up Docker Buildx
+  #     uses: docker/setup-buildx-action@v3
+  #   - name: Build and push
+  #     uses: docker/build-push-action@v6
+  #     with:
+  #       context: .
+  #       push: true
+  #       tags: arvindpdige/bankapp:actions
+  #       file: ./Dockerfile
+
+  deploy:
+    runs-on: self-hosted  
+    steps:
+    - name: Deploy to Kubernetes
+      uses: appleboy/ssh-action@master
       with:
-        username: ${{ secrets.DOCKER_HUB_USERNAME }}
-        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
-    - name: Set up QEMU
-      uses: docker/setup-qemu-action@v3
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v3
-    - name: Build and push
-      uses: docker/build-push-action@v6
-      with:
-        context: .
-        push: true
-        tags: arvindpdige/bankapp:actions
-        file: ./Dockerfile
+        host: 127.0.0.1
+        username: ${{ secrets.K8S_MASTER_NODE_USERNAME }}
+        key: ${{ secrets.K8S_MASTER_NODE_SSH_KEY }}
+        script: |
+          # kubectl set image deployment/bankapp-deployment bankapp=arvindpdige/bankapp:actions -n blue-green
+          # kubectl rollout status deployment/bankapp-deployment -n blue-green
+          kubectl get pods -A
+          kubectl get ns
+          kubectl get svc -n blue-green
+          #kubectl get all -n blue-green
 
